const test = require('node:test');
const assert = require('node:assert/strict');
const { emailLookup, decryptPii, encryptedUserFields } = require('../utils/userEmailCrypto');

// Fixed, public test vector generated by the Python importer's HKDF/HMAC/AES-GCM format.
const TEST_KEY = 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=';
const EMAIL_CIPHERTEXT = 'AAECAwQFBgcICQoLia-1R52dsupz8LqhhkMfQFwIkXNrUD67y3T39qOUMzLl';

test('email lookup matches the Python importer and normalizes case and whitespace', () => {
  const original = process.env.BASE64_KEY;
  const originalOverride = process.env.USER_DATA_ENCRYPTION_KEY;
  try {
    delete process.env.USER_DATA_ENCRYPTION_KEY;
    process.env.BASE64_KEY = TEST_KEY;
    assert.equal(
      emailLookup('  Alice@Example.com  '),
      '4f90051a1796d08bd8165cc033e6a3566a756f186852202c6709c36650521127'
    );
    assert.equal(decryptPii(EMAIL_CIPHERTEXT, 'user_email'), 'alice@example.com');
    assert.throws(() => decryptPii(EMAIL_CIPHERTEXT, 'user_name'));
  } finally {
    if (original === undefined) delete process.env.BASE64_KEY;
    else process.env.BASE64_KEY = original;
    if (originalOverride === undefined) delete process.env.USER_DATA_ENCRYPTION_KEY;
    else process.env.USER_DATA_ENCRYPTION_KEY = originalOverride;
  }
});

test('new account fields round-trip through AES-GCM and use the normalized email', () => {
  const original = process.env.BASE64_KEY;
  const originalOverride = process.env.USER_DATA_ENCRYPTION_KEY;
  try {
    delete process.env.USER_DATA_ENCRYPTION_KEY;
    process.env.BASE64_KEY = TEST_KEY;
    const fields = encryptedUserFields('  Alice@Example.com  ', 'Alice', '+91 90000 00000');
    assert.equal(fields.user_email, 'alice@example.com');
    assert.equal(fields.user_email_lookup, emailLookup(fields.user_email));
    assert.equal(decryptPii(fields.user_email_enc, 'user_email'), fields.user_email);
    assert.equal(decryptPii(fields.user_name_enc, 'user_name'), 'Alice');
    assert.equal(decryptPii(fields.user_contact_num_enc, 'user_contact_num'), '+91 90000 00000');
    assert.notEqual(encryptedUserFields(fields.user_email, 'Alice', null).user_email_enc, fields.user_email_enc);
    assert.throws(() => encryptedUserFields('', 'Alice', null));
    assert.throws(() => encryptedUserFields('alice@example.com', '', null));
  } finally {
    if (original === undefined) delete process.env.BASE64_KEY;
    else process.env.BASE64_KEY = original;
    if (originalOverride === undefined) delete process.env.USER_DATA_ENCRYPTION_KEY;
    else process.env.USER_DATA_ENCRYPTION_KEY = originalOverride;
  }
});
