info:
  name: Trainee Profile in VR
  type: http
  seq: 4

http:
  method: GET
  url: http://{{local_base_url}}/api/v1/trainee/49982e50-c723-472a-9dd0-524eb7f5dc15?isVr=true
  params:
    - name: isVr
      value: "true"
      type: query
  body:
    type: json
    data: ""
  auth:
    type: bearer
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX21haWwiOiJyb2hpbnRoQGh0aWMuaWl0bS5hYy5pbiIsInJvbGUiOiIxMDMiLCJjZW50cmVfaWQiOiIwMWM2OWJkMS1kNjJlLTQ4M2UtYjA5Zi1mMTRhMmYwZjQzZWQiLCJjZW50ZXJfbmFtZSI6IkhUSUMgSW50ZXJuYWwgVGVhbSIsImlhdCI6MTc4OTAzOTQ3NH0.PdTXhpUMBxY4pF4u8aJwK5K477Wg3CC4-lWPskWrqcs

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: true
