info:
  name: Trainee Profile in VR
  type: http
  seq: 4

http:
  method: GET
  url: http://{{base_url_prod}}/api/v1/trainee/b6baabec-3423-4131-8e6f-f59494f397c2?isVr=false
  params:
    - name: isVr
      value: "false"
      type: query
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
